### ISSUE TITLE
(Feature Request?)Klipper logo X243 upside down

### ISSUE THREAD

**Issue by decker9000** [audiobrian/tld3pro_klipper#2]
klipper_logo_X243.tft loads on my LCD upside down, I rotated the entire display but have an eye sore of partial border visible.
Any chance we could get a flipped version of klipper_logo_X243.tft? I tried the 343 rotated version but it's incompatible with my display.

Thanks!
![IMG_2591](https://github.com/audiobrian/tld3pro_klipper/assets/13543117/3d3175d6-bc43-4ca6-aa55-087132967b74)

**Comment by audiobrian** [comment]
Can you share a photo of the back of your screen?

**Comment by decker9000** [comment]
> Can you share a photo of the back of your screen?
 
![IMG_2520](https://github.com/audiobrian/tld3pro_klipper/assets/13543117/2819b452-ff6c-42f9-8eec-0742e02d7473)

**Comment by audiobrian** [comment]
Let me see if I can recompile the X243 version

**Comment by audiobrian** [comment]
@decker9000 can you check this version? https://github.com/audiobrian/tld3pro_klipper/blob/master/tft/klipper_logo_X243_rotated.tft

**Comment by decker9000** [comment]
Having another issue with my display complaining there is multiple TFT files on SD card when only one. Once I resolve that I'll test and let you know

**Comment by decker9000** [comment]
Finally got my screen firmware to update and the rotated logo worked perfectly
